components:
  - name: file_upload
    type: flask
    source:
      git:
        url: "https://github.com/NIRANJANGOPALAN/file-upload.git"
        branch: master
    build:
      command: pip install -r requirements.txt
    deploy:
      command: python app.py
    env:
      - name: FLASK_ENV
        value: production